### ISSUE TITLE
Implement live updates of the api when running with docker

### ISSUE THREAD

**Issue by JamesRobionyRogers** [JamesRobionyRogers/Assignment01-VirtualisingSoftware#8]
> I have a dockerfile that runs a backend python flask rest api. I then have a docker compose file that runs the docker file. 
>
> Is there any way that I can have the api update live as I edit the code from the running container via docker compose?

---

Certainly! I'll guide you through the modifications needed in both your Dockerfile and docker-compose.yaml to enable live updates of your Flask API. 

## 1. Modifying the Dockerfile

Your current Dockerfile is already close to what we need. We'll make a few small changes:

```Dockerfile
# Use an official Python runtime as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port that the app runs on
EXPOSE 5001

# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=development
ENV FLASK_DEBUG=1

# Run the Flask application
CMD ["flask", "run", "--port=5001"]
```

Key changes:
- Removed the `COPY . .` line, as we'll be mounting the code directory instead.
- Added `ENV FLASK_ENV=development` and `ENV FLASK_DEBUG=1` to enable Flask's debug mode and auto-reloading.

## 2. Modifying the docker-compose.yaml

Now, let's update your docker-compose.yaml file:

```yaml
name: jobtracker

include: 
  - path: 
    - ./database/docker-compose.yml

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend/api
    ports:
      - "5001:5001"
    volumes:
      - ./backend/api:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: flask run --port=5001 --host=0.0.0.0

  db-init:
    build: ./database/init
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
```

Key changes in the `backend` service:
- Added a `volumes` section to mount your local code directory into the container.
- Added `environment` variables to ensure Flask runs in debug mode.
- Added a `command` to explicitly run Flask with the correct host and port.

## 3. Ensuring your Flask app is configured correctly

In your main Flask application file (app.py or whatever you've named it), make sure you have something like this:

```python
if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5001)
```

This ensures that when you run the app directly (not through Flask CLI), it uses the correct settings.

## 4. Running your updated setup

1. Make sure you're in the directory containing your docker-compose.yaml file.
2. Run `docker-compose up --build` to build and start your services.
3. Your Flask API should now be running and will automatically reload when you make changes to your code.

## Additional Notes:

- The `volumes` section in docker-compose mounts your local `./backend/api` directory to `/app` in the container. Adjust this path if your project structure is different.
- You may need to restart your Docker containers if you add new dependencies to your requirements.txt file.
- This setup is great for development but remember to use a production-ready configuration when deploying to production.

With these changes, you should be able to edit your Flask API code and see the changes reflected immediately without having to rebuild or restart your Docker containers.
